# version: "3.9"

services:
  rclone:
    container_name: rclone
    entrypoint: [ "/bin/sh" ]
    environment:
      - TZ=Asia/Shanghai
    hostname: rclone
    image: rclone/rclone:latest
    network_mode: "host"
    # privileged: true
    restart: always
    tty: true
    volumes:
      - /home/gd:/home/gd
